config/routes.rb
Urps2::Application.routes.draw do
  resources :permissions

  resources :interactions

  resources :roles

  resources :controller_actions  do
    collection do
      post 'edit_multiple'
      put 'update_multiple'
    end
  end

  resources :controller_names

  resources :action_names

end

app/models/action_name.rb
class ActionName < ActiveRecord::Base
  has_many :controller_actions
end

app/controllers/action_names_controller.rb
class ActionNamesController < ApplicationController
  before_action :set_action_name, only: [:show, :edit, :update, :destroy]

  # GET /action_names
  # GET /action_names.json
  def index
    @action_names = ActionName.all
  end

  # GET /action_names/1
  # GET /action_names/1.json
  def show
  end

  # GET /action_names/new
  def new
    @action_name = ActionName.new
  end

  # GET /action_names/1/edit
  def edit
  end

  # POST /action_names
  # POST /action_names.json
  def create
    @action_name = ActionName.new(action_name_params)

    respond_to do |format|
      if @action_name.save
        format.html { redirect_to @action_name, notice: 'Action name was successfully created.' }
        format.json { render action: 'show', status: :created, location: @action_name }
      else
        format.html { render action: 'new' }
        format.json { render json: @action_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /action_names/1
  # PATCH/PUT /action_names/1.json
  def update
    respond_to do |format|
      if @action_name.update(action_name_params)
        format.html { redirect_to @action_name, notice: 'Action name was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @action_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /action_names/1
  # DELETE /action_names/1.json
  def destroy
    @action_name.destroy
    respond_to do |format|
      format.html { redirect_to action_names_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_action_name
      @action_name = ActionName.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def action_name_params
      params.require(:action_name).permit(:name)
    end
end

app/helpers/action_names_helper.rb
module ActionNamesHelper
end

app/views/action_names/_form.html.erb
<%= form_for(@action_name) do |f| %>
  <% if @action_name.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@action_name.errors.count, "error") %> prohibited this action_name from being saved:</h2>

      <ul>
      <% @action_name.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/action_names/edit.html.erb
<h1>Editing action_name</h1>

<%= render 'form' %>

<%= link_to 'Show', @action_name %> |
<%= link_to 'Back', action_names_path %>

app/views/action_names/index.html.erb
<h1>Listing action_names</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @action_names.each do |action_name| %>
    <tr>
      <td><%= action_name.name %></td>
      <td><%= link_to 'Show', action_name %></td>
      <td><%= link_to 'Edit', edit_action_name_path(action_name) %></td>
      <td><%= link_to 'Destroy', action_name, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Action name', new_action_name_path %>

app/views/action_names/new.html.erb
<h1>New action_name</h1>

<%= render 'form' %>

<%= link_to 'Back', action_names_path %>

app/views/action_names/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @action_name.name %>
</p>


<%= link_to 'Edit', edit_action_name_path(@action_name) %> |
<%= link_to 'Back', action_names_path %>