config/routes.rb
Urps2::Application.routes.draw do
  resources :permissions

  resources :interactions

  resources :roles

  resources :controller_actions  do
    collection do
      post 'edit_multiple'
      put 'update_multiple'
    end
  end

  resources :controller_names

  resources :action_names

end

app/controllers/controller_actions_controller.rb
class ControllerActionsController < ApplicationController
  before_action :set_controller_action, only: [:show, :edit, :update, :destroy]
  before_filter :process_permissions_attrs, only: [:create, :update, :update_multiple]

  def process_permissions_attrs
    if params[:controller_action].is_a? Hash  # Single
      params[:controller_action][:interactions_attributes].values.each do |per_attr|
        per_attr[:_destroy] = true if per_attr[:enable] != '1'
      end
      a=1
    else # collection
    end
  end

  # GET /controller_actions
  # GET /controller_actions.json
  def index
    @actions = ActionName.all
    @controllers = ControllerName.all
    @controller_actions = ControllerAction.all
  end

  # GET /controller_actions/1
  # GET /controller_actions/1.json
  def show
  end

  # GET /controller_actions/new
  def new
    @controller_action = ControllerAction.new
  end

  # GET /controller_actions/1/edit
  def edit
  end

  # POST /controller_actions
  # POST /controller_actions.json
  def create
    @controller_action = ControllerAction.new(controller_action_params)

    respond_to do |format|
      if @controller_action.save
        format.html { redirect_to @controller_action, notice: 'Controller action was successfully created.' }
        format.json { render action: 'show', status: :created, location: @controller_action }
      else
        format.html { render action: 'new' }
        format.json { render json: @controller_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /controller_actions/1
  # PATCH/PUT /controller_actions/1.json
  def update
    respond_to do |format|
      if @controller_action.update(controller_action_params)
        format.html { redirect_to @controller_action, notice: 'Controller action was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @controller_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /controller_actions/1
  # DELETE /controller_actions/1.json
  def destroy
    @controller_action.destroy
    respond_to do |format|
      format.html { redirect_to controller_actions_url }
      format.json { head :no_content }
    end
  end


  def edit_multiple
    @edit_multiple_commit = params[:commit]
    @edit_multiple_action = params[:actions]
    if params[:commit] == 'Edit Action'
      @title = "Editing action " + ActionName.find(params[:actions]).name.capitalize + " for all Controllers"
      @controller_actions = ControllerAction.actions(params[:actions]).all
    else
      @title = "Editing controller " + ControllerName.find(params[:controllers]).name.capitalize + " for all Actions"
      @controller_actions = ControllerAction.controllers(params[:controllers]).all
    end
  end

  def update_multiple
    @edit_multiple = params[:commit]
    if params[:commit] == 'Edit Action'
      @title = "Editing action " + ActionName.find(params[:actions]).name.capitalize + " for all Controllers"
      @controller_actions = ControllerAction.actions(params[:actions]).all
    else
 #     @title = "Editing controller " + ControllerName.find(params[:controllers]).name.capitalize + " for all Actions"
      @controller_actions = ControllerAction.controllers(params[:controllers]).all
    end

    respond_to do |format|
      if @controller_actions.update(controller_actions_params)
        format.html { redirect_to @controller_action, notice: 'Controller action was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @controller_action.errors, status: :unprocessable_entity }
      end
    end
    if @controller_actions.empty?
      flash[:notice] = "Products updated"
      redirect_to products_url
    else
      render :action => "edit_individual"
    end
    @controller_actions = ControllerAction(params[:controller_action]).all
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_controller_action
      @controller_action = ControllerAction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def controller_action_params
      params.require(:controller_action).permit!
    end
    def controller_actions_params
      params.require(:controller_actions).permit!
    end
end

app/helpers/controller_actions_helper.rb
module ControllerActionsHelper
end

app/views/controller_actions/_form.html.erb
<%= form_for(@controller_action) do |f| %>
  <% if @controller_action.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@controller_action.errors.count, "error") %> prohibited this controller_action from being saved:</h2>

      <ul>
      <% @controller_action.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div>
      <h2><%= f.label :role %></h2>
      <%= f.fields_for :interactions, @controller_action.initialized_interactions() do |builder| %>
          <% role = builder.object.role %>
          <%= builder.hidden_field :role_id %>

          <div class="field">
            <%= builder.check_box :enable %>
            <%= builder.label :enable, role.name %>
          </div>
      <% end %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>

<% end %>

app/views/controller_actions/edit.html.erb
<h1>Editing controller_action</h1>

<%= render 'form' %>

<%= link_to 'Show', @controller_action %> |
<%= link_to 'Back', controller_actions_path %>

app/views/controller_actions/edit_multiple.html.erb
<h1><%= @title %></h1>

<%= form_for( @controller_actions, :url => update_multiple_controller_actions_path, :html => { :method => :put }) do |f| %>

    <% for ca in @controller_actions %>
      <% @controller_action = ca %>
        <% if @controller_action.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@controller_action.errors.count, "error") %> prohibited this controller_action from being saved:</h2>

          <ul>
            <% @controller_action.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= field_set_tag do %>
        <h2><%= f.label "Roles for #{ca.name} " %></h2>
        <div>

          <%= f.fields_for :interactions, @controller_action.initialized_interactions() do |builder| %>
              <% role = builder.object.role %>
              <%= builder.hidden_field :role_id %>

              <div class="field">
                <%= builder.check_box :enable %>
                <%= builder.label :enable, role.name %>
              </div>
          <% end %>
        </div>
        <% end %>
    <% end %>
    <p><%= f.submit @edit_multiple_commit %></p>
<% end %>

<%= link_to 'Back', controller_actions_path %>

app/views/controller_actions/index.html.erb
<%= form_tag( {action: :edit_multiple}, method: :post) do %>
    <h1>Listing actions</h1>
    <p>
      <%= select_tag :actions, options_from_collection_for_select(@actions,:id, :name) %>
      <%= submit_tag "Edit Action" %>
    </p>
    <h1>Listing controllers</h1>

    <p>
      <%= select_tag :controllers, options_from_collection_for_select(@controllers,:id, :name) %>
      <%= submit_tag "Edit Controller" %>
    </p>
    <h1>Listing controller_actions</h1>

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @controller_actions.each do |controller_action| %>
        <tr>
          <td><%= controller_action.name %></td>
          <td><%= link_to 'Show', controller_action %></td>
          <td><%= link_to 'Edit', edit_controller_action_path(controller_action) %></td>
          <td><%= link_to 'Destroy', controller_action, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

    <br />
<% end %>

<%= link_to 'New Controller action', new_controller_action_path %>

app/views/controller_actions/new.html.erb
<h1>New controller_action</h1>

<%= render 'form' %>

<%= link_to 'Back', controller_actions_path %>

app/views/controller_actions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @controller_action.name %>
</p>

<p>
  <strong>Action name:</strong>
  <%= @controller_action.action_name %>
</p>

<p>
  <strong>Controller name:</strong>
  <%= @controller_action.controller_name %>
</p>


<%= link_to 'Edit', edit_controller_action_path(@controller_action) %> |
<%= link_to 'Back', controller_actions_path %>