config/routes.rb
Urps2::Application.routes.draw do
  resources :permissions

  resources :interactions

  resources :roles

  resources :controller_actions  do
    collection do
      post 'edit_multiple'
      put 'update_multiple'
    end
  end

  resources :controller_names

  resources :action_names

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
  def secure_form_for(record_or_name_or_array, *args, &block)
    options = args.extract_options!
    form_for(record_or_name_or_array, *(args << options.merge(builder: SecureFormBuilder)), &block)
  end
end
class SecureFormBuilder < ActionView::Helpers::FormBuilder
  def label(method, text = nil, options = {}, &block)
    super #@template.label(@object_name, method, text, objectify_options(options), &block)
  end
end

app/views/application/_action_name_roles.html.erb
<div>
    <h2><%= f.label r %></h2>
    <%= f.fields_for :interactions, s.initialized_interactions() do |builder| %>
        <% role = builder.object.role %>
        <%= builder.hidden_field :role_id %>

        <div class="field">
            <%= builder.check_box :enable %>
            <%= builder.label :enable, role.name %>
        </div>
    <% end %>
</div>

app/views/application/_controller_name_roles.html.erb
<div>
    <h2><%= f.label r %></h2>
    <%= f.fields_for :interactions, s.initialized_interactions() do |builder| %>
        <% role = builder.object.role %>
        <%= builder.hidden_field :role_id %>

        <div class="field">
            <%= builder.check_box :enable %>
            <%= builder.label :enable, role.name %>
        </div>
    <% end %>
</div>

app/views/application/_demo_menu.html.erb
<h2>
  <%= link_to "Roles", roles_path %> |
  <%= link_to "All Resources", controller_actions_path %>
  <%= link_to "One Action All Controllers", action_names_path %>
  <%= link_to "One Controller All Actions", controller_names_path %>
</h2>

app/views/application/_scoped_controller_actions.html.erb
<% cas.each do |ca| %>
    <%= label_tag :name, "ControllerName " + ca.name %>
    <%= f.fields_for :interactions, ca.initialized_interactions(ca.id) do |builder| %>
        <% role = builder.object.role %>
        <%= builder.hidden_field :role_id %>

        <div class="field">
          <%= builder.check_box :enable %>
          <%= builder.label :enable, role.name %>
        </div>
    <% end %>
<% end %>

app/views/application/_user_roles.html.erb
<div>
    <h2><%= f.label r %></h2>
    <%= f.fields_for :interactions, s.initialized_interactions() do |builder| %>
        <% role = builder.object.role %>
        <%= builder.hidden_field :role_id %>

        <div class="field">
            <%= builder.check_box :enable %>
            <%= builder.label :enable, role.name %>
        </div>
    <% end %>
</div>